app/core/urls.py
from django.urls import path

from .views import news_list_view


app_name = "core"
urlpatterns = [
    path("", news_list_view, name="news_list"),
]

app/scraper/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/models.py
from django.db import models
from django.db.models import Q


class NewsItemQuerySet(models.QuerySet):
    def search(self, query):
        return self.filter(Q(title__icontains=query) |
                           Q(author__icontains=query) |
                           Q(source__icontains=query))


class NewsItemManager(models.Manager):
    def get_queryset(self):
        return NewsItemQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class NewsItem(models.Model):
    source = models.CharField(max_length=255)
    link = models.TextField()
    author = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    publish_date = models.DateField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = NewsItemManager()

    def __str__(self):
        return f"{self.source}-{self.title}"

app/core/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core.paginator import Paginator

from .models import NewsItem
from .tasks import scrape_dev_to_task, scrape_hacker_news_task


def news_list_ordering(request, qs):
    source = request.GET.get("source", None)
    author = request.GET.get("author", None)
    title = request.GET.get("title", None)
    date = request.GET.get("date", None)

    if source:
        qs = qs.order_by(
            "-source") if source == "desc" else qs.order_by("source")
    elif author:
        qs = qs.order_by(
            "-author") if author == "desc" else qs.order_by("author")
    elif title:
        qs = qs.order_by(
            "-title") if title == "desc" else qs.order_by("title")
    elif date:
        qs = qs.order_by(
            "-publish_date") if date == "desc" else qs.order_by("publish_date")
    else:
        qs = qs.order_by("-created")

    return qs


def news_list_view(request):
    query = request.GET.get("q", None)
    page_number = request.GET.get("page")
    articles = NewsItem.objects.all()

    if not articles.count():
        scrape_hacker_news_task.delay()
        scrape_dev_to_task.delay()

    if query:
        articles = articles.search(query)

    articles = news_list_ordering(request, articles)
    paginator = Paginator(articles, 15)
    
    context = {
        "object_list": paginator.get_page(page_number),
        "total_count": articles.count(),
    }
    return render(request, "news_list.html", context)

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/main.min.css" %}" />

    <title>Django Scraper</title>
  </head>
  <body>
    {% include "navbar.html" %}

    <main role="main" class="container">

    {% block content  %}
    {% endblock content %}

    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/navbar.html
<nav class="navbar navbar-expand-md sticky-top shadow-sm navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand text-primary fs-4 fw-normal" href="{% url 'core:news_list' %}">DJ Scraper</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/news_list.html
{% extends "base.html" %}

{% block content %}
    <div class="mt-3">
        
        <div class="d-flex justify-content-between align-items-center flex-column flex-md-row">
            {% include "pagination.html" with page_obj=object_list %}
            <div class="my-3 d-none d-md-block">
                {% if request.GET.q %}
                    <p class="d-inline">Result Count: <span class="text-primary">{{ total_count }}</span></p>
                {% else %}
                    <p class="d-inline">Articles Count: <span class="text-primary">{{ total_count }}</span></p>
                {% endif %} 
            </div>
        </div>
        
        <form method="GET">
            <div class="input-group input-group-sm mb-3">
                <input name="q" type="text" class="form-control" value="{{ request.GET.q }}" placeholder="Search article, author, source" aria-label="Search article, author, source" aria-describedby="button-addon2">
                <button class="btn btn-outline-primary" type="submit" id="button-addon">Search</button>
            </div>
        </form>

        <div class="table-responsive">
            <table class="table table-hover caption-top">
                <caption class="p-0">List of articles</caption>
                <thead class="table-dark">
                    <tr>
                        <th scope="col">
                            <form method="GET">
                                <input type="hidden" name="source" {% if request.GET.source == "asc" %}value="desc"{% else %}value="asc"{% endif %}>
                                <button class="link-light border-0 text-reset bg-transparent" type="submit">Source<span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-arrow-down-up" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M11.5 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L11 2.707V14.5a.5.5 0 0 0 .5.5zm-7-14a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V1.5a.5.5 0 0 1 .5-.5z"/>
                                    </svg>
                                </span></button>
                            </form>
                        </th>
                        <th scope="col">
                            <form method="GET">
                                <input type="hidden" name="author" {% if request.GET.author == "asc" %}value="desc"{% else %}value="asc"{% endif %}>
                                <button class="link-light border-0 text-reset bg-transparent" type="submit">Author<span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-arrow-down-up" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M11.5 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L11 2.707V14.5a.5.5 0 0 0 .5.5zm-7-14a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V1.5a.5.5 0 0 1 .5-.5z"/>
                                    </svg>
                                </span></button>
                            </form>
                        </th>
                        <th scope="col">
                            <form method="GET">
                                <input type="hidden" name="title" {% if request.GET.title == "asc" %}value="desc"{% else %}value="asc"{% endif %}>
                                <button class="link-light border-0 text-reset bg-transparent" type="submit">Title<span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-arrow-down-up" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M11.5 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L11 2.707V14.5a.5.5 0 0 0 .5.5zm-7-14a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V1.5a.5.5 0 0 1 .5-.5z"/>
                                    </svg>
                                </span></button>
                            </form>
                        </th>
                        <th scope="col">
                            <form method="GET">
                                <input type="hidden" name="date" {% if request.GET.date == "asc" %}value="desc"{% else %}value="asc"{% endif %}>
                                <button class="link-light border-0 text-reset bg-transparent" type="submit">Publish Date<span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-arrow-down-up" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M11.5 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L11 2.707V14.5a.5.5 0 0 0 .5.5zm-7-14a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L4 13.293V1.5a.5.5 0 0 1 .5-.5z"/>
                                    </svg>
                                </span></button>
                            </form>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                        <tr>
                            <th><a class="text-reset text-decoration-none" href="https://{{ item.source }}" target="_blank">{{ item.source }}</a></th>
                            <td>{{ item.author }}</td>
                            <td><a class="text-decoration-none" href="{{ item.link }}" target="_blank" >{{ item.title }}</a></td>
                            <td>{{ item.publish_date }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="text-center" colspan="4">No Records found...</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock content %}

app/templates/pagination.html
{% load my_tags %}

<nav>
    <ul class="pagination pagination-sm mb-3 mb-md-0">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.previous_page_number  %}"><span aria-hidden="true">&laquo;</span></a></li>
            {% if page_obj.number > 3 %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">1</a></li>
                {% if page_obj.number > 4 %}
                  <li class="page-item disabled"><a class="page-link"><span>...</span></a></li>
                {% endif %}
            {% endif %}
        {% else %}
            <li class="page-item disabled"><a class="page-link"><span aria-hidden="true">&laquo;</span></a></li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item"><a class="page-link current-page" href="?{% param_replace page=num %}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=num %}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            {% if page_obj.number < page_obj.paginator.num_pages|add:"-3" %}
                <li class="page-item"><a class="page-link"><span>...</span></a></li>
                <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
            {% elif page_obj.number < page_obj.paginator.num_pages|add:"-2" %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}"><span aria-hidden="true">&raquo;</span></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><span aria-hidden="true">&raquo;</span></a></li>
        {% endif %}
    </ul>
</nav>